---
title: "01_c"
author: "Kaixin"
date: "2023-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/SMobility_paper_v2/02_data_validation/")
```


```{r initial, include=FALSE}
library(tidyverse)
library(lubridate)
library(data.table)
library(ggrepel)
library(sf)
library(hrbrthemes)
library(scales)
library(RColorBrewer)
options(max.print = 100)
options(datatable.print.topn = 50)


ifile_usercount <-
  "result/01_a_usercount_city_level.csv"
ifile_pr_info <-
  "result/01_b_province_info.csv"
ifile_census <-
  "data/01_c_census_province/01_census2020_province_34.csv"

odir_result <-
  "result/"
```


```{r color_setting, include=FALSE}
# 查看颜色盘
# display.brewer.all(
#   # "div", "qual", "seq"
#   type = "all", 
#   # Number of different colors in the palette, minimum 3, maximum depending on palette
#   n = NULL 
#   )

# 选择颜色
display.brewer.pal(n = 8, name = "Set1")
pal <- brewer.pal(n = 8, name = "Set1") %>% rev()
pal
```


```{r input_data}
usercount <- 
  fread(ifile_usercount)

pr_info <- 
  fread(ifile_pr_info)

census <- 
  fread(ifile_census) %>%
  .[, .(native, pop_2020)]
```


```{r data_process}
usercount_pr <-
  merge(usercount,
        pr_info[, .(city_join, pr)],
        all.x = T,
        by.x = "city",
        by.y = "city_join") %>%
  .[, .(usercount = sum(usercount, na.rm = T)), by = pr] %>%
  .[, usercount_prop := usercount/sum(usercount, na.rm = T)]

usercount_pr_info <-
  merge(usercount_pr,
        pr_info[, .(pr, pr_pinyin, abbreviation, region)] %>% unique(),
        all.x = T,
        by = "pr")

census_prop <-
  census[, pop_2020_prop := pop_2020/sum(pop_2020, na.rm = T)]

lm_data <-
  merge(usercount_pr_info,
        census_prop,
        all.x = T,
        by.x = "pr",
        by.y = "native")
```


```{r lm_analysis}
ols1 <- lm(usercount_prop ~ pop_2020_prop, data = lm_data)
summary(ols1)
```


```{r plot}
plot1 <-
  ggplot(lm_data, 
         aes(x = usercount_prop, 
             y = pop_2020_prop)) +
  geom_point(alpha = 1, 
             aes(color = region)) +
  # geom_segment(mapping = aes(x = 0.001,
  #                            xend = 0.1,
  #                            y = 0.001,
  #                            yend = 0.1),
  #              color = "blue",
  #              linewidth = 0.5) +
  geom_smooth(
    mapping = aes(
      x = usercount_prop,
      y = pop_2020_prop
    ),
    method = "lm",
    color = "grey40",
    linewidth = 0.5,
    alpha = 0.2
  ) + 
  geom_text_repel(aes(label = abbreviation),
                  size = unit(3, "pt"),
                  max.time = 10,
                  max.iter = 1e3) +
  annotate("text",
           x = 0.09,
           y = 0.003,
           label = expression(y[census] == 0.897*x[users] + 0.003,
                              "R-squared = 0.68\n\n",
                              "p-value < 0.001\n"),
           # label = expression(atop("Histogram of "*hat(mu), 
           #             Bootstrap~samples * ',' ~Allianz)),
           # label = expression(atop(y[census] == 0.897*x[users] + 0.003,
           #                         "R-squared = 0.68p-value < 0.001")),
           size = 4,
           vjust = "inward",
           hjust = 1) +
  scale_color_manual(values = pal) +
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x, 2),
                labels = trans_format("log10", math_format(10^.x)),
                # limits = c(1e-3-0.00015, 0.12)
                limits = c(1e-3+0.0015, 0.12)
                ) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x, 2),
                labels = trans_format("log10", math_format(10^.x)),
                # limits = c(1e-3-0.00015, 0.12)
                limits = c(1e-3+0.0015, 0.12)
                ) +
  labs(x = "users (% of tot)",
       y = "census (% of tot)",
       color = "Region") +
  theme_bw() +
  theme(axis.text = element_text(color = "black"),
        aspect.ratio = 1,
        legend.position = c(0.17, 0.65),   ### 需要调整
        legend.key.height = unit(14, "pt"),
        legend.background = element_rect(fill = "transparent", colour = NA),
        legend.key = element_rect(fill = NA, color = NA),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(linewidth = 1)
        ) +
  guides(color = guide_legend(nrow = 8))

print(plot1)
```


```{r save_plot, eval=FALSE}
time <-
  str_sub(as.character(now()), start = 1, end = -8) %>%
  str_replace(" ", "_")

filename_temp <- paste0("01_plot_", time, ".pdf")

ggsave(filename = filename_temp,
       plot = plot1,
       path = odir_result,
       width = 108,
       height = 105,
       units = "mm",
       dpi = 300)
```



```{r extract_pr_abbre, eval=FALSE}
pr_extract <-
  pr_info[pr_pinyin != "", .(pr_pinyin, abbreviation)] %>% 
  unique() %>%
  .[str_detect(pr_pinyin, "Ningxia Hui"), pr_pinyin := "Ningxia"] %>%
  .[str_detect(pr_pinyin, "Nei Mongol"), pr_pinyin := "Inner Mongolia"] %>%
  .[str_detect(pr_pinyin, "Xinjiang Uygur"), pr_pinyin := "Xinjiang"] %>%
  .[str_detect(pr_pinyin, "Xizang"), pr_pinyin := "Tibet"] %>%
  .[order(abbreviation)]

pr_extract_str <- NULL

for (i in 1:nrow(pr_extract)) {
  str <- paste0(pr_extract$abbreviation[i], ", ", pr_extract$pr_pinyin[i], "; ")
  pr_extract_str <- paste0(pr_extract_str, str)
}

print(pr_extract_str)
```











