---
title: "figure3_test_representativeness"
author: "Kaixin"
date: "2023-06-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Socialmedia_Mobility/")
```


```{r initial, include=FALSE}
library(tidyverse)
library(lubridate)
library(data.table)
library(ggrepel)
library(scales)
library(RColorBrewer)
library(grid)
library(cowplot)
options(max.print = 100)
options(datatable.print.topn = 50)

odir_plot <-
  "publication/figure3_test_representativeness/"
```


```{r color_preset}
source("publication/color_setting.R")
pal <- brewer.pal(n = 8, name = "Set1") %>% rev()
```


# figure 3a

```{r file_path_figure_3a, include=FALSE}
ifile_usernum <-
  "data/processed/04_usernum_city_level.csv"
ifile_pr_info <-
  "data/processed/04_province_info.csv"
ifile_census <-
  "data/raw/figure3_census_2020_province/01_census2020_province_34.csv"
```


```{r input_data_figure_3a}
usernum <- 
  fread(ifile_usernum)

pr_info <- 
  fread(ifile_pr_info)

census <- 
  fread(ifile_census) %>%
  .[, .(native, pop_2020)]
```


```{r linear_model_data}
usernum_pr <-
  merge(usernum,
        pr_info[, .(city_join, pr)],
        all.x = T,
        by.x = "city",
        by.y = "city_join") %>%
  .[, .(usernum = sum(usernum, na.rm = T)), by = pr] %>%
  .[, usernum_prop := usernum/sum(usernum, na.rm = T)]

usernum_pr_info <-
  merge(usernum_pr,
        pr_info[, .(pr, pr_pinyin, abbreviation, region)] %>% unique(),
        all.x = T,
        by = "pr")

census_prop <-
  census[, pop_2020_prop := pop_2020/sum(pop_2020, na.rm = T)]

lm_data <-
  merge(usernum_pr_info,
        census_prop,
        all.x = T,
        by.x = "pr",
        by.y = "native")
```


```{r linear_model_analysis}
ols1 <- lm(usernum_prop ~ pop_2020_prop, data = lm_data)
summary(ols1)
```


```{r plot_figure_3a}
plot1 <-
  ggplot(lm_data, 
         aes(x = usernum_prop, 
             y = pop_2020_prop)) +
  geom_point(alpha = 1, 
             aes(color = region)) +
  geom_smooth(mapping = aes(x = usernum_prop,
                            y = pop_2020_prop),
    method = "lm",
    color = "grey40",
    linewidth = 0.5,
    alpha = 0.2) + 
  geom_text_repel(aes(label = abbreviation),
                  size = unit(3, "pt"),
                  max.time = 10,
                  max.iter = 1e3) +
  annotate("text",
           x = 0.09,
           y = 0.0025,
           label = expression(y[census] == 0.897*x[users] + 0.004,
                              "R-squared = 0.683\n\n",
                              "p-value < 0.001\n"),
           size = 4,
           vjust = "inward",
           hjust = 1) +
  scale_color_manual(values = pal) +
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x, 2),
                labels = trans_format("log10", math_format(10^.x)),
                limits = c(1e-3+0.0015, 0.12)
                ) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x, 2),
                labels = trans_format("log10", math_format(10^.x)),
                limits = c(1e-3+0.0015, 0.12)
                ) +
  labs(x = "Users (% of tot)",
       y = "Census (% of tot)",
       color = "Region") +
  theme_bw() +
  theme(axis.text = element_text(color = "black"),
        axis.title.x = element_text(margin = margin(t = 15)),
        aspect.ratio = 1,
        legend.position = c(0.17, 0.65),
        legend.key.height = unit(14, "pt"),
        legend.background = element_rect(fill = "transparent", colour = NA),
        legend.key = element_rect(fill = NA, color = NA),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(linewidth = 1)) +
  guides(color = guide_legend(nrow = 8))

# print(plot1)
```


# figure 3b

```{r file_path_figure_3b, include=FALSE}
ifile_userinfo <-
  "data/processed/04_userinfo.csv.gz"
ifile_yearbook <-
  "data/raw/figure3_yearbook_2021_age_gender.csv"
```


```{r input_data_figure_3b}
userinfo <-
  fread(ifile_userinfo)

yearbook <-
  fread(ifile_yearbook) %>%
  .[, .(age_group = Age, Male_percent, Female_percent)]
```


```{r userinfo_filter_statistic}
userinfo_filter <-
  userinfo[(gender != "") & (!is.na(age))] %>%
  .[, age_group := fcase(age >= 0 & age <= 14, "0-14",
                         age >= 15 & age <= 24, "15-24",
                         age >= 25 & age <= 59, "25-59",
                         age >= 60, "60-",
                         default = NA)] %>%
  .[!is.na(age_group)]

userinfo_stat <-
  userinfo_filter[, .(age_group_num = .N), by = .(gender, age_group)] %>%
  .[, age_group_prop := age_group_num/sum(age_group_num, na.rm = T)]
```


```{r prepare_plotdata}
userinfo_plotdata <-
  userinfo_stat[, age_group_prop := ifelse(gender == "Male", age_group_prop*(-1), age_group_prop)] %>%
  .[, .(age_group, gender, age_group_prop)]

yearbook_plotdata <-
  melt(yearbook,
       measure.vars = c("Male_percent", "Female_percent"),
       variable.name = "gender",
       value.name = "age_group_prop") %>%
  .[, gender := str_replace(gender, "_percent", "")] %>%
  .[, age_group_prop := ifelse(gender == "Male", age_group_prop*(-1), age_group_prop)] %>%
  .[, .(age_group, gender, age_group_prop)]

plotdata <-
  rbind(userinfo_plotdata[, datasource := "Weibo"],
        yearbook_plotdata[, datasource := "Population"])

# percent
plotdata[, age_group_prop_percent := 
           paste0(round(age_group_prop, digits = 3)*100, "%")] %>%
  .[, age_group_prop_percent := str_replace(age_group_prop_percent, "-", "")]

plotdata[, axis_percent := fcase(age_group_prop < 0, age_group_prop - 0.01,
                                 age_group_prop >= 0, age_group_prop + 0.01)]

summary(plotdata)
```


```{r plot_figure_3b}
plot2 <-
  ggplot() +
  geom_bar(data = plotdata,
           mapping = aes(x = age_group,
                         y = age_group_prop,
                         fill = datasource
                         ),
           width = 0.7,
           stat = "identity",
           position = "dodge"
           ) +
  scale_fill_manual(name = "source",
                    values = c("Weibo" = color_primary[6],
                               "Population" = color_primary[1]
                               )) +
  geom_hline(yintercept = 0,
             color = "black",
             linetype = "dashed") +
  geom_text(data = plotdata[gender == "Male"],
            mapping = aes(x = age_group,
                          y = axis_percent,
                          label = age_group_prop_percent,
                          group = datasource
                          ),
            position = position_dodge(width = 0.7), 
            hjust = 1,
            size = unit(2.5, "pt")
            ) +
  geom_text(data = plotdata[gender == "Female"],
            mapping = aes(x = age_group,
                          y = axis_percent,
                          label = age_group_prop_percent,
                          group = datasource
                          ),
            position = position_dodge(width = 0.7), 
            hjust = 0,
            size = unit(2.5, "pt")
            ) +
  coord_flip(clip = "off") +
  scale_y_continuous(limits = c(-0.4, 0.4),
                     breaks = seq(-0.4, 0.4, 0.2),
                     labels = c("40%", "20%", "0", "20%", "40%"),
                     expand = c(0.035, 0.035)) +
  scale_x_discrete(labels = c("0-14" = "0-14",
                              "15-24" = "15-24",
                              "25-59" = "25-59",
                              "60-" = "60+")) +
  labs(x = "Age") +
  theme_bw() +
  theme(axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(margin = margin(r = 0.5, unit = 'cm')),
        legend.key.size = unit(1, "line"),
        legend.box.margin = margin(t = 0.3, unit = "cm"),
        panel.grid = element_blank()) +
  annotation_custom(grob = linesGrob(arrow = arrow(type = "open",
                                                   ends = "both",
                                                   length = unit(1.25 ,"mm")),
                                     gp = gpar(col = "black",
                                               lwd = 1.5)),
                    xmin = -0.07, xmax = -0.07, ymin = -Inf, ymax = 0) +
  annotation_custom(grob = linesGrob(arrow = arrow(type = "open",
                                                   ends = "both",
                                                   length = unit(1.25 ,"mm")),
                                     gp = gpar(col = "black",
                                               lwd = 1.5)),
                    xmin = -0.07, xmax = -0.07, ymin = 0, ymax = Inf) +
  annotation_custom(grob = grid::textGrob(label = "Male",
                                          vjust = -0.6,
                                          gp = gpar(col = "black", 
                                                    fontsize = 9)),
                    xmin = -0.08, xmax = -0.08, ymin = -0.2, ymax = -0.2) +
  annotation_custom(grob = grid::textGrob(label = "Female", 
                                          vjust = -0.6,
                                          gp = gpar(col = "black", 
                                                    fontsize = 9),
                                          ),
                    xmin = -0.08, xmax = -0.08, ymin = 0.2, ymax = 0.2)

# print(plot2)
```


# figure 3

```{r save_plot_figure3}
p_3 <-
  plot_grid(plot1, plot2, 
            align = "h", axis = "b", 
            labels = c("a", "b"), vjust = 1.3,
            nrow = 1, rel_widths = c(2, 1.25))

figure_name <- "figure3.pdf"

ggsave(filename = figure_name,
       plot = p_3,
       path = odir_plot,
       width = 180,
       height = 115,
       units = "mm",
       dpi = 300)
```


















