---
title: "03_plot_beijing_checkins_spatial_distribution"
author: "Kaixin"
date: '2023-03-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/SMobility_paper_v2/03_checkins_distribution/")
```


```{r initial, include=FALSE}
library(tidyverse)
library(data.table)
library(sf)
library(raster)
library(ggspatial)
library(RColorBrewer)
library(scales)
library(lubridate)
library(janitor)

ifile_checkins_lonlat <-
  "result/01_checkins_link_lonlat.csv"

ifile_beijing_dlg_1 <-
  "data/02_Beijing_DLG_data/J50.gdb.zip"

ifile_beijing_dlg_2 <-
  "data/02_Beijing_DLG_data/K50.gdb.zip"

odir_result <- 
  "result/"
```


```{r color_setting, include=FALSE}
# 查看颜色盘
display.brewer.all(
  # "div", "qual", "seq"
  type = "all", 
  # Number of different colors in the palette, minimum 3, maximum depending on palette
  n = NULL 
  )

# 选择颜色
display.brewer.pal(n = 6, name = "Set1")
pal_map <- brewer.pal(n = 6, name = "Set1") %>% rev()
pal_map
```


```{r inputdata}
## WGS 84 大地坐标
crs_84 <- st_crs("EPSG:4326")
## Albers Equal Area Conic投影
crs_al <- st_crs("+proj=aea +lat_1=25 +lat_2=47 +lon_0=105")


# WGS84
checkins_lonlat <-
  fread(ifile_checkins_lonlat) %>%
  filter(category_google != "") %>%
  filter(category_google != "Others" & category_google != "Education")

# CGCS2000
beijing_dlg_1 <-
  st_layers(ifile_beijing_dlg_1)

# CGCS2000
beijing_dlg_2 <-
  st_layers(ifile_beijing_dlg_2)
```


```{r read_feature_class}
beijing_adm <-
  c("东城区", "西城区", "朝阳区", "丰台区", "石景山区", "海淀区", "顺义区", 
    "通州区", "大兴区", "房山区", "门头沟区", "昌平区", "平谷区", "密云区",
    "怀柔区", "延庆区")

# border
beijing_border_1 <-
  st_read(dsn = ifile_beijing_dlg_1, layer = "BOUA") %>%
  filter(NAME %in% beijing_adm)

beijing_border_2 <-
  st_read(dsn = ifile_beijing_dlg_2, layer = "BOUA") %>%
  filter(NAME %in% beijing_adm)

sf_use_s2(FALSE)

beijing_border <-
  bind_rows(beijing_border_1, beijing_border_2) %>%
  group_by(PAC) %>%
  summarise(SHAPE = st_union(SHAPE),
            SHAPE_Area = sum(SHAPE_Area, na.rm = T)) %>%
  st_transform(crs = crs_84)

# road
beijing_road_1 <-
  st_read(dsn = ifile_beijing_dlg_1, layer = "LRDL")

beijing_road_2 <-
  st_read(dsn = ifile_beijing_dlg_2, layer = "LRDL")

beijing_road <-
  bind_rows(beijing_road_1, beijing_road_2) %>%
  st_transform(crs = crs_84)
```


```{r plot_beijing_dlg, eval=FALSE}
ggplot() + 
  geom_sf(data = beijing_road,
          color = "grey80",
          linewidth = 0.2) +
  geom_sf(data = beijing_border,
          fill = NA,
          color = "grey50",
          linewidth = 0.2) +
  scale_x_continuous(expand = c(0, 0),
                     limits = c(116, 116.8)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(39.65, 40.25)) +
  theme_bw()
```


```{r checkins_raster}
checkins_grid <-
  # 按照经纬度进行切片
  checkins_lonlat[, ':='(lon_cut = cut(lon, 
                                       breaks = seq(-180, 180, 0.001),
                                       include.lowest = T), 
                         lat_cut = cut(lat,
                                       breaks = seq(-90, 90, 0.001),
                                       include.lowest = T))] %>% 
  # 统计每个切片的签到数量
  .[, .(checkins_num = sum(checkins_num, na.rm = T)), by = .(lon_cut, lat_cut, category_google)] %>%
  .[, checkins_num_log := log(checkins_num, base = 10)] %>%
  # 计算每个切片的中心点经纬度
  .[, ':='(lon_grid = as.double(lon_cut)*0.001-180.0005,
           lat_grid = as.double(lat_cut)*0.001-90.0005)]

summary(checkins_grid)
```


```{r plot}
checkins_grid_filter <-
  checkins_grid[checkins_num_log >= 3] %>%  ### 筛选显示的最低数量
  .[, category_google := factor(category_google, 
                              levels = c("Residential",
                                         "Workplaces",
                                         "Retail & recreation",
                                         "Parks",
                                         "Transit stations",
                                         "Grocery & pharmacy"))]

plot <-
  ggplot() +
  coord_sf(crs = crs_al,
           default_crs = crs_84) +
  geom_sf(data = beijing_road,
          color = "grey70",
          linewidth = 0.2) +
  geom_sf(data = beijing_border,
          fill = NA,
          color = "grey20",
          linewidth = 0.3) +
  geom_point(data = checkins_grid_filter,
             mapping = aes(x = lon_grid,
                           y = lat_grid,
                           color = category_google,
                           size = checkins_num_log),
             alpha = 0.5  ### 需要调整
             ) +
  scale_color_manual(name = NULL, # "Places"
                     values = pal_map
                     ) +
  scale_size(name = "Number of\nposts",
             range = c(1, 6),  ### 需要调整
             breaks = seq(0, 5, 1),
             labels = c(expression(10^0),
                        expression(10^1),
                        expression(10^2),
                        expression(10^3),
                        expression(10^4),
                        expression(10^5))) +
  # 调整地图绘制范围
  scale_x_continuous(expand = c(0, 0),
                     limits = c(116.12, 116.62),
                     breaks = seq(116.1, 116.6, 0.1)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(39.74, 40.04),
                     breaks = seq(39.7, 40.1, 0.1)) +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text = element_text(color = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = unit(6, "pt"),  ### 需要调整
                                   lineheight = unit(0.5, "pt")  ### 需要调整
                                   ),
        legend.margin = margin(t = -5, l = 0, r = 0, b = 0),  ### 需要调整
        legend.box.margin = margin(l = -35),  ### 需要调整
        legend.spacing.x = unit(0, "pt"),  ### 需要调整
        legend.title = element_text(margin = margin(l = unit(20, "pt")), ### 需要调整
                                    size = unit(6, "pt")  ### 需要调整
                                    ),
        legend.key.height = unit(10, "pt") ### 需要调整
        ) +
  guides(color = guide_legend(nrow = 2),
         size = guide_legend(nrow = 1, 
                             title.vjust = 0.5
                             )) +
  annotation_scale(location = "bl") + # 设置距离刻度尺
  annotation_north_arrow(location = "tl", 
                         style = north_arrow_nautical(fill = c("grey40", 
                                                               "white"), 
                                                      line_col = "grey20"))

print(plot)
```


```{r save_plot, eval=TRUE}
time <-
  str_sub(as.character(now()), start = 1, end = -8) %>%
  str_replace(" ", "_")

filename_temp <- paste0("03_plot_", time, ".png")

ggsave(filename = filename_temp,
       plot = plot,
       path = odir_result,
       width = 121,
       height = 130,
       units = "mm",
       dpi = 300)
```


