project:
  type: website

website:
  title: "Social media Mobility"
  navbar:
    title: "CASGIS"

format:
  html:
    theme: Simplex
    # theme: cosmo
    css: my-styles.css
    toc: true

editor: visual

# left:
#   - icon: fa-github
#     href: https://github.com/CASGIS/Socialmedia_Mobility
# right:
#   - href: index.qmd
#     text: Data
#   - href: about.qmd
#     text: About
