project:
  type: website

website:
  title: "website"
  navbar:
    title: "CASGIS123"
    left:
      - icon: fa-github
        href: https://github.com/CASGIS/Socialmedia_Mobility

format:
  html:
    theme: Simplex
    # theme: cosmo
    css: my-styles.css
    toc: true

editor: visual

#   - href: index.qmd
#     text: Data
#   - href: about.qmd
#     text: About
# right: