---
title: ""
author: "Kaixin"
date: "2023-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/weibo/17_checkins_cleaning/03_full_sample/")
```


```{r initial, include=FALSE}
library(tidyverse)
library(data.table)
library(lubridate)
library(zoo)
library(patchwork)

ifile_checkins <-
  "data/04_checkins_domestic.csv.gz"
odir_data <-
  "data/"
odir_result <-
  "result/"
```


```{r rawdata, include=FALSE}
checkins <- 
  fread(ifile_checkins, nThread = 14) %>%
  .[, userid := as.character(userid)]
```


```{r categorygoogle_data}
checkins_categorygoogle <-
  checkins[category_google != ""] %>%
  .[(category_google != "Education") & (category_google != "Others")]
```


```{r pois_filter_v2}
# 使用checkins,不使用checkins_category

period_0 <-
  c(ymd("2018-10-01"):ymd("2020-02-01"))  # "2020-02-01"

period_1 <-
  c(ymd("2020-03-01"):ymd("2020-12-31"))

poi_res_2019 <-
  checkins[created_at %in% period_0, .(containerid = unique(containerid))]

poi_res_2020 <-
  checkins[created_at %in% period_1, .(containerid = unique(containerid))]

poi_filter <-
  setdiff(poi_res_2020, poi_res_2019)

poi_filter_user <-
  checkins[created_at %in% period_1] %>%
  .[poi_filter, on = "containerid", nomatch = 0] %>%
  .[, .(userid = unique(userid))]
```


```{r user_freq}
user_freq <-
  checkins %>%
  .[poi_filter_user, on = "userid", nomatch = 0] %>%
  .[, ':='(year = year(created_at), month = month(created_at))] %>%
  .[, ymonth := ymd(paste0(year,
                           "-",
                           str_pad(month, 2, "left"),
                           "-01"))] %>%
  .[, .(postcount = .N), by = .(userid, ymonth)]
```


```{r user_freq_filter}
user_freq_filter_before <-
  user_freq %>%
  .[ymonth < ymd("2020-04-01")] %>%
  .[, .(month_posted = .N), by = .(userid)] %>%
  .[, .(userid = unique(userid))]


user_freq_filter <-
  user_freq %>%
  .[ymonth >= ymd("2020-04-01")] %>%
  .[, .(month_posted = .N), by = .(userid)] %>%
  .[, .(userid = unique(userid))]

user_freq_filter_result <-
  setdiff(user_freq_filter[, .(userid)], user_freq_filter_before[, .(userid)])
```


```{r poi_filter_supple_checkins}
period_1 <-
  c(ymd("2020-03-01"):ymd("2020-12-31"))

checkins_supple_residential <-
  checkins_categorygoogle[created_at %in% period_1] %>%
  .[category_google == "Residential"] %>%
  .[poi_filter_user, on = "userid", nomatch = 0] %>%
  .[sample(.N, .N*5/12)]


checkins_remove_retail <-
  checkins_categorygoogle[created_at %in% period_1] %>%
  .[category_google == "Retail & recreation"] %>%
  .[poi_filter_user, on = "userid", nomatch = 0]
```


```{r plot}
user_filter_final <-
  setdiff(poi_filter_user, user_freq_filter_result)

checkins_define <- 
  checkins_categorygoogle %>%
  .[!user_filter_final, on = "userid"] %>%
  rbind(checkins_supple_residential) %>%
  .[!checkins_remove_retail, on = "bid"]


category_list <- 
  c("Parks",
    "Retail & recreation",
    "Grocery & pharmacy",
    "Workplaces",
    "Transit stations",
    "Residential")

p1 <- NULL

for(i in 1:length(category_list)){
  
  postcount_category <-
    checkins_define[category_google == category_list[i]] %>%
    .[, .(postcount_category = .N), by = .(created_at)]
  
  postcount_category_7MA <-
    postcount_category[order(created_at)] %>%
    .[, postcount_category_7MA := rollmean(postcount_category, k = 7, fill = NA)]
  
  plot <-
    ggplot(postcount_category_7MA) +
    geom_line(aes(x = created_at, 
                  y = postcount_category_7MA),
              linewidth = 0.5) +
    scale_x_date(limits = c(ymd("2018-10-01"), NA)) +
    labs(title = paste0(category_list[i], "_7MA")) 
  
  if(i == 1){
    p1 <- plot
  } else{
    p1 <- p1 / plot
  }
  
}

p2 <- NULL

for(i in 1:length(category_list)){
  
  poicount_category <-
    checkins_define[category_google == category_list[i]] %>%
    .[, .(poicount_category = uniqueN(containerid)), by = .(created_at)]
  
  poicount_category_7MA <-
    poicount_category[order(created_at)] %>%
    .[, poicount_category_7MA := rollmean(poicount_category, k = 7, fill = NA)]
  
  plot <-
    ggplot(poicount_category_7MA) +
    geom_line(aes(x = created_at, 
                  y = poicount_category_7MA),
              linewidth = 0.5) +
    scale_x_date(limits = c(ymd("2018-10-01"), NA)) +
    labs(title = paste0(category_list[i], "_7MA")) 
  
  if(i == 1){
    p2 <- plot
  } else{
    p2 <- p2 / plot
  }
  
}

plot_result <- p1 | p2

time <-
  paste0(str_replace(now(), " ", "_"))

ggsave(plot_result,
       filename = paste0("Rplot_postcount_category_", time, ".png"),
       path = odir_result,
       width = 12,
       height = 15)
```


```{r save_result, eval=FALSE}
# 使用checkins,而不是checkins_categorygoogle
checkins_filter <- 
  checkins %>%
  .[!user_filter_final, on = "userid"] %>%
  rbind(checkins_supple_residential) %>%
  .[!checkins_remove_retail, on = "bid"]

fwrite(checkins_filter,
       paste0(odir_data, paste0("06_checkins_filter.csv.gz")))
```








